name: Validate Variables

on:
  workflow_call:
    inputs:
      variables:
        required: true
        type: string

jobs:
  validate:
    name: Validate Variables
    if: ${{ inputs.variables != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variable: ${{ fromJson(inputs.variables) }}
    steps:
      - name: Validate ${{ matrix.variable }}
        env:
          VARIABLE: ${{ secrets[matrix.variable] }}
        if: ${{ env.VARIABLE == '' && vars[matrix.variable] == '' }}
        run: |
          echo "ERROR: ${{ matrix.variable }} secret does not exist in the workflow."
          exit 1